// docs/tools-list.md, generated from the tool folders: one row per tool, nothing written by hand.

export interface ToolRow {
  id: string;
  name: string;
  category: string;
  runtime: string;
  summary: string;
}

const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();

/** The Markdown of the list. `categoryNames` maps a category id to its display name. */
export function renderToolsList(
  rows: readonly ToolRow[],
  categoryNames: ReadonlyMap<string, string>,
): string {
  const sorted = [...rows].sort(
    (a, b) =>
      (categoryNames.get(a.category) ?? a.category).localeCompare(
        categoryNames.get(b.category) ?? b.category,
      ) || a.id.localeCompare(b.id),
  );
  return `${[
    "# Tools list",
    "",
    "Generated by `pnpm tools:list` from the tool folders: do not edit by hand. Run it again after you add, rename or remove a tool.",
    "",
    `${sorted.length} tools.`,
    "",
    "| id | name | category | runtime | summary |",
    "| --- | --- | --- | --- | --- |",
    ...sorted.map(
      (row) =>
        `| ${cell(row.id)} | ${cell(row.name)} | ${cell(categoryNames.get(row.category) ?? row.category)} | ${cell(row.runtime)} | ${cell(row.summary)} |`,
    ),
  ].join("\n")}\n`;
}
